name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Swift
        uses: actions/setup-swift@v2
        with:
          swift-version: '5.7.2'
      - name: Install dependencies
        run: swift package resolve
      - name: Test
        run: xcodebuild test -scheme PokemonClub -destination 'platform=iOS Simulator,name=iPhone 14 Pro' -sdk iphonesimulator -enableCodeCoverage YES
      - name: Build
        run: swift build --package-path PokemonClub.xcodeproj
